apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  type: ExternalName
  externalName: "kafka1"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
spec:
  type: ExternalName
  externalName: "kafka2"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
spec:
  type: ExternalName
  externalName: "kafka3"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka4
spec:
  type: ExternalName
  externalName: "kafka4"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka5
spec:
  type: ExternalName
  externalName: "kafka5"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka6
spec:
  type: ExternalName
  externalName: "kafka6"
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
