apiVersion: v1
kind: Service
metadata:
  name: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  labels:
    name: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      name: openobserve
      app: openobserve
  template:
    metadata:
      labels:
        name: openobserve
        app: openobserve
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
      - name: openobserve
        image: public.ecr.aws/zinclabs/openobserve:latest
        env:
        - name: ZO_ROOT_USER_EMAIL
          valueFrom:
            configMapKeyRef:
              name: openobserve-config
              key: email
        - name: ZO_ROOT_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: openobserve-config
              key: password
        - name: ZO_DATA_DIR
          value: /data
        resources:
          limits:
            cpu: 4096m
            memory: 2048Mi
          requests:
            cpu: 256m
            memory: 50Mi
        ports:
        - containerPort: 5080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: openobserve-0
  type: NodePort
  ports:
  - port: 5080
    nodePort: 31000
