all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
  hosts:
    node1:
      ansible_host: 192.168.60.4
      ip: 192.168.60.4
      access_ip: 192.168.60.4
    node2:
      ansible_host: 192.168.60.5
      ip: 192.168.60.5
      access_ip: 192.168.60.5
    node3:
      ansible_host: 192.168.60.6
      ip: 192.168.60.6
      access_ip: 192.168.60.6
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
