all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
  hosts:
    node1:
      ansible_host: '1'
      ip: '1'
      access_ip: '1'
    node2:
      ansible_host: '2'
      ip: '2'
      access_ip: '2'
    node3:
      ansible_host: '3'
      ip: '3'
      access_ip: '3'
    node4:
      ansible_host: '4'
      ip: '4'
      access_ip: '4'
    node5:
      ansible_host: '5'
      ip: '5'
      access_ip: '5'
    node6:
      ansible_host: '6'
      ip: '6'
      access_ip: '6'
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
