name: Docker CI
run-name: Build & Push to Container Registry
on:
    push:
      branches:
        main
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.6, 3.8]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: ghcr.io
                logout: true
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                logout: true
            - name: Set lowercase owner name
              run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
              env:
                OWNER: '${{ github.repository_owner }}'
            - name: build and push to registry
              uses: docker/build-push-action@v4
              with:
                context: .
                file: Dockerfile.python
                push: true
                build-args:
                  PYTHON_VERSION=${{ matrix.python-version }}
                tags: |
                  ${{ env.OWNER_LC }}/python:${{ matrix.PYTHON_VERSION }}-ihr
                  ghcr.io/${{ env.OWNER_LC }}/python:${{ matrix.python-version }}-ihr